apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: filebeat
  namespace: monitoring
  labels:
    app: filebeat
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: filebeat
      type: ds
  template:
    metadata:
      labels:
        app: filebeat
        type: ds
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.2.4
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yaml
          subPath: filebeat.yaml
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: filebeat-config
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
  labels:
    app: filebeat
data:
  filebeat.yaml: |
    name: ${HOSTNAME}
    filebeat.prospectors:
      - type: log
        enabled: true
        paths:
          - /var/lib/docker/containers/*/*.log
        exclude_files: [logging\.log$]
        fields_under_root: true
        fields: {tags : ['AppId:MicroService', 'AppName:MicroService', 'AppVersion:1.0.0', 'AppPath:/var/lib/docker/containers/', 'fileType:log', 'logType:MICROSERVICE', 'companyProfile:${SM_PROFILE_COMPANY_NAME:MyCompany}', 'index:${FILEBEAT_ES_INDEX:pulse}'], fileType: 'log', os: '${OSTYPE:linux-gnu}', user: '${USER:centos}'}
        json.keys_under_root: true
        json.add_error_key: true
        close_inactive: 1m
        ignore_older: 2m
        tail_files: true

      - type: log
        enabled: true
        paths:
          - /var/lib/docker/containers/*/config.*.json
        json.keys_under_root: true
        json.add_error_key: true
        fields_under_root: true
        fields: {tags : ['AppId:MicroService', 'AppName:MicroService', 'AppVersion:1.0.0', 'AppPath:/var/lib/docker/containers/', 'fileType:config', 'logType:MICROSERVICE', 'companyProfile:${SM_PROFILE_COMPANY_NAME:MyCompany}', 'index:${FILEBEAT_ES_INDEX:pulse}'], fileType: 'config', os: '${OSTYPE:linux-gnu}', user: '${USER:centos}'}

    filebeat.shutdown_timeout: 5s

    output.logstash:
      hosts: ["{{LOGSTASH}}"]

