#!groovy

pipeline {

    agent {
        label 'kubectl-node'
    }

    parameters {
        choice(name: 'COMMAND', choices: 'plan\ncreate\ndestroy', description: 'Action to take regarding deployment.')

    }



    options {
        ansiColor('xterm')
        timeout(time: 1, unit: 'HOURS')
    }
    stages {

        stage('Configure') {
            steps {
                dir('.') {
                    sh 'bash platform.sh'
                }
            }
       }
    }
}

